service: latency-injection-demo

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  tracing: true
  versionFunctions: false

  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    - Effect: 'Allow'
      Action: 'ssm:GetParameters'
      Resource: 
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/public-api-a.config'
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/public-api-b.config'
        - 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/internal-api.config'
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/latency-injection-demo-${self:provider.stage}"

functions:
  public-api-a:
    handler: functions/public-api-a.handler
    events:
      - http:
          path: /public-a
          method: get

  public-api-b:
    handler: functions/public-api-b.handler
    events:
      - http:
          path: /public-b
          method: get

  internal-api:
    handler: functions/internal-api.handler
    events:
      - http:
          path: /internal
          method: get

resources:
  Resources:
    DynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: latency-injection-demo-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1